repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-xml
          - id: check-toml
          - id: check-added-large-files
    - repo: https://github.com/WGUNDERWOOD/tex-fmt
      rev: v0.5.4
      hooks:
          - id: tex-fmt
